(Feature, Demo) "Load more ballots" button for "All" tab
oraclesorg/oracles-dapps-voting pull request #138
Opened 2018-06-15 16:06 UTC by varasev

- (Mandatory) Description
This PR makes `Voting DApp` display only first ten ballots and display "Load more ballots" button below ballots list in "All" section. Relates to https://github.com/poanetwork/poa-dapps-voting/issues/124, https://github.com/poanetwork/poa-dapps-voting/issues/128 and https://github.com/poanetwork/poa-dapps-voting/issues/132.

- (Mandatory) What is it: (Fix), (Feature) or (Refactor)
(Feature)

2018-06-19 15:54 UTC, vbaranov requested changes
Relates to https://github.com/poanetwork/poa-dapps-voting/pull/139#pullrequestreview-130043146

2018-06-21 18:03 UTC, vbaranov reviewed
@varasev looks good to me. Should we merge it or leave it, as you provided collapsing of `demo` and `core` branches?

2018-06-22 08:03 UTC, varasev commented
@vbaranov It's better to merge that because the current `poa-test-setup` in https://github.com/poanetwork/poa-test-setup still uses `demo` branch of `poa-dapps-voting` as a submodule. I'll make PR in `poa-test-setup` later for switching to `core` branch.

2018-06-22 11:04 UTC, vbaranov approved these changes

2018-06-22 11:04 UTC, merged