(Fix) Checking transaction status when voting or finalizing
oraclesorg/oracles-dapps-voting pull request #145
Opened 2018-07-02 10:07 UTC by varasev

- (Mandatory) Description
Transaction status is not checked when voting for a ballot or a ballot finalizing. Relates to https://github.com/poanetwork/poa-dapps-voting/issues/123 and https://github.com/poanetwork/poa-dapps-voting/issues/144.

- (Mandatory) What is it: (Fix), (Feature) or (Refactor)
(Fix)

2018-07-03 13:07 UTC, vbaranov requested changes
It seems that contract methods execution handler could be implemented as a separate function:
```
if (tx.status === true || tx.status === '0x1') {
                swal("Congratulations!", messages.VOTED_SUCCESS_MSG, "success").then((result) => {
                    push(`${commonStore.rootPath}`);
                });
            } else {
                swal("Warning!", messages.VOTE_FAILED_TX, "warning").then((result) => {
                });
            }
```

2018-07-03 13:07 UTC, vbaranov commented on src/messages.js
> +Make sure you don't have Transaction Error. Exception thrown in contract code message in metamask before you sign it.`
metamask -> Metamask

2018-07-03 13:07 UTC, vbaranov commented on src/messages.js
> +Exception thrown in contract code message in metamask before you sign it.`
metamask -> Metamask

2018-07-03 13:07 UTC, vbaranov commented on src/components/NewBallot.jsx
> +          swal("Warning!", messages.BALLOT_CREATE_FAILED_TX, "warning").then((result) => {
Let's remove`.then((result) => {})`

2018-07-03 13:07 UTC, vbaranov commented on src/components/BallotCard.jsx
> +                swal("Warning!", messages.VOTE_FAILED_TX, "warning").then((result) => {
Let's remove`.then((result) => {})`

2018-07-04 07:02 UTC, varasev commented
> It seems that contract methods execution handler could be implemented as a separate function

@vbaranov yes, but in the next PR #146 these functions have different implementations, so I suggest to leave them as they are:
- https://github.com/varasev/poa-dapps-voting/blob/d52d5f59157ab4820607920dc0059977a86a34fb/src/components/BallotCard.jsx#L187-L211
- https://github.com/varasev/poa-dapps-voting/blob/d52d5f59157ab4820607920dc0059977a86a34fb/src/components/BallotCard.jsx#L253-L265

> metamask -> Metamask
> Let's remove `.then((result) => {})`

Ok, I fixed these in https://github.com/poanetwork/poa-dapps-voting/pull/146 (commit https://github.com/poanetwork/poa-dapps-voting/pull/146/commits/d52d5f59157ab4820607920dc0059977a86a34fb) as it covers all changes from this #145 PR.

2018-07-04 11:04 UTC, vbaranov approved these changes

2018-07-04 11:04 UTC, merged