(Feature) Add new styles to DApp.
oraclesorg/oracles-dapps-voting pull request #166
Opened 2018-08-08 19:34 UTC by gabitoesmiapodo

**Description:**

Solves https://github.com/poanetwork/poa-dapps-voting/issues/164 by adding the new syles..

**What is it:** (Feature)

**Additional Info:**

I'm attaching a few screen captures to know what to expect from this update.

Core designs:

<img width="436" alt="ballot-tablet-v" src="https://user-images.githubusercontent.com/4015436/43859805-20d01042-9b28-11e8-9709-d5e0e4fa434f.png">
<img width="1026" alt="new-desktop" src="https://user-images.githubusercontent.com/4015436/43859806-20faf316-9b28-11e8-8735-ab2499e8bf92.png">
<img width="435" alt="new-tablet-v" src="https://user-images.githubusercontent.com/4015436/43859807-211a8b68-9b28-11e8-8756-ceb9909f0c54.png">
<img width="361" alt="mobile-menu" src="https://user-images.githubusercontent.com/4015436/43859808-2146e62c-9b28-11e8-8b41-d2af2df8ed5a.png">
<img width="322" alt="new-mobile" src="https://user-images.githubusercontent.com/4015436/43859809-2167dc10-9b28-11e8-9f34-68921f850bea.png">
<img width="935" alt="new-tablet-h" src="https://user-images.githubusercontent.com/4015436/43859810-2194a3f8-9b28-11e8-8abc-d9569730c231.png">
<img width="1026" alt="ballot-desktop" src="https://user-images.githubusercontent.com/4015436/43859811-21bbc38e-9b28-11e8-97da-6f04da656198.png">
<img width="322" alt="ballot-mobile" src="https://user-images.githubusercontent.com/4015436/43859812-21f36eec-9b28-11e8-80d9-01a58956f94d.png">
<img width="931" alt="ballot-tablet-h" src="https://user-images.githubusercontent.com/4015436/43859813-221948ce-9b28-11e8-945f-6f7a3d96f4ca.png">
<img width="325" alt="loading" src="https://user-images.githubusercontent.com/4015436/43859814-224d30c6-9b28-11e8-8cd2-32edb7581e81.png">

Sokol designs:

<img width="1026" alt="new-desktop-sokol" src="https://user-images.githubusercontent.com/4015436/43859867-4471af7e-9b28-11e8-8d0f-7f146f27e63e.png">
<img width="428" alt="ballot-tablet-v-sokol" src="https://user-images.githubusercontent.com/4015436/43859868-44944b24-9b28-11e8-8b5d-023ffb3659cc.png">
<img width="434" alt="new-tablet-v-sokol" src="https://user-images.githubusercontent.com/4015436/43859870-44c26f22-9b28-11e8-8f84-f8bd72d90fbc.png">
<img width="320" alt="mobile-menu-sokol" src="https://user-images.githubusercontent.com/4015436/43859871-44e51bda-9b28-11e8-867b-f03ca1a2c4f2.png">
<img width="1025" alt="ballot-desktop-sokol" src="https://user-images.githubusercontent.com/4015436/43859872-450b615a-9b28-11e8-827a-8713bc1827dc.png">
<img width="932" alt="new-tablet-h-sokol" src="https://user-images.githubusercontent.com/4015436/43859873-453827e4-9b28-11e8-870b-f8d59e9e92c2.png">
<img width="320" alt="loading-sokol" src="https://user-images.githubusercontent.com/4015436/43859874-455cd5a8-9b28-11e8-94c3-9a70623c7d52.png">
<img width="320" alt="ballot-mobile-sokol" src="https://user-images.githubusercontent.com/4015436/43859875-4580a082-9b28-11e8-902b-452672d5f658.png">
<img width="935" alt="ballot-tablet-h-sokol" src="https://user-images.githubusercontent.com/4015436/43859876-45a4810a-9b28-11e8-8108-06f75f052e0d.png">
<img width="319" alt="new-mobile-sokol" src="https://user-images.githubusercontent.com/4015436/43859877-45ca38dc-9b28-11e8-9283-577815579eb3.png">

2018-08-09 07:20 UTC, varasev commented
The description lines are bound to the upper border of the icon:


![image](https://user-images.githubusercontent.com/33550681/43884030-b035f95a-9bbd-11e8-801d-a7b36530c909.png)


Maybe add `padding-top: 5px;` for `.ballots .info` to make it look like this?

![image](https://user-images.githubusercontent.com/33550681/43884039-b6edb8b4-9bbd-11e8-96cb-fefca966fc04.png)

2018-08-09 12:53 UTC, gabitoesmiapodo commented
@varasev Fixed it.

2018-08-09 13:28 UTC, vbaranov requested changes
@gabitoesmiapodo 
1. Style for ballot creation button should be changed: 'NEW BALLOT' -> 'New Ballot'
2. Key type and Action values in a ballot card should be in lower case with a first capital letter
3. Padding between sliders should be more than padding between a slider and corresponding button
![2018-08-09 16 16 13](https://user-images.githubusercontent.com/4341812/43901251-b5f48e6a-9bef-11e8-8c34-3c34d1d241e4.png)
4. 
![2018-08-09 16 21 07](https://user-images.githubusercontent.com/4341812/43901608-8d278e6e-9bf0-11e8-9db7-68779755646a.png)
5. More.../Less buttons should have another color than text. Please see the original layout.

2018-08-09 14:17 UTC, gabitoesmiapodo commented
@vbaranov

Good catches, sorry about that. 

- Style for ballot creation button should be changed: 'NEW BALLOT' -> 'New Ballot' -> Fixed.

- Key type and Action values in a ballot card should be in lower case with a first capital letter -> Changed it.

- Padding between sliders should be more than padding between a slider and corresponding button -> Fixed.

- All paddings inside card should be equal. -> Done.

- More.../Less buttons should have another color than text. Please see the original layout. -> Changed that too.

2018-08-09 14:35 UTC, vbaranov commented
@gabitoesmiapodo yes, looks good now, thanks. Could you also add small paddings between columns here:

![2018-08-09 17 32 01](https://user-images.githubusercontent.com/4341812/43905717-4df361be-9bfa-11e8-8a21-eac34101c3b4.png)

?

2018-08-09 16:20 UTC, varasev commented
@gabitoesmiapodo I think the `Load More Ballots` button should be more visible - maybe with some border or background?

2018-08-09 16:27 UTC, vbaranov commented
>I think the Load More Ballots button should be more visible - maybe with some border or background?

@varasev there is no borders or another background from designer's layout https://user-images.githubusercontent.com/16716926/43633724-bfffce10-9712-11e8-9a53-527247032d3c.png. I guess, we should follow it.

2018-08-09 16:40 UTC, varasev commented
> @varasev there is no borders or another background from designer's layout https://user-images.githubusercontent.com/16716926/43633724-bfffce10-9712-11e8-9a53-527247032d3c.png. I guess, we should follow it.

Maybe make that button just with bold font then? Or make the top and the bottom whitespace around it wider?

2018-08-09 16:51 UTC, vbaranov commented
>Maybe make that button just with bold font then? Or make the top and the bottom whitespace around it wider?

maybe, but it should be agreed with an author of the layout https://github.com/poanetwork/poa-dapps-voting/issues/164#issuecomment-410188165.

2018-08-09 17:28 UTC, gabitoesmiapodo commented
@vbaranov Added the paddings.

@varasev Maybe we should ask @pashagonchar ?

2018-08-10 05:48 UTC, varasev commented
Sorry, didn't guess initially who is designer here :)

2018-08-10 05:57 UTC, varasev commented
Ballot description is shown with some words broken near the right border: 

![image](https://user-images.githubusercontent.com/33550681/43941079-5cd0ed42-9c7b-11e8-8933-1adbc0978e95.png)

Could we turn on a word wrapping?

2018-08-10 06:03 UTC, varasev commented
Padding is also needed here:

![image](https://user-images.githubusercontent.com/33550681/43941309-48bc6fb0-9c7c-11e8-880e-7c04f4db5e80.png)

2018-08-10 06:14 UTC, varasev commented
`Ballot time` column is in the wrong place for `min threshold` and `change proxy` ballot types. You can find it if you click on `Load More Ballots` several times:

![image](https://user-images.githubusercontent.com/33550681/43941632-8e6354ce-9c7d-11e8-990a-2efb848b18ea.png)

![image](https://user-images.githubusercontent.com/33550681/43941641-9573bf92-9c7d-11e8-9109-c921bd990c8a.png)

2018-08-10 07:04 UTC, varasev commented
@pashagonchar @gabitoesmiapodo Some little defects with the search bar:

![image](https://user-images.githubusercontent.com/33550681/43943561-ab85a85c-9c84-11e8-9547-79ad3d3f9ae4.png)

![image](https://user-images.githubusercontent.com/33550681/43943572-b3ade030-9c84-11e8-8f15-1353526feab7.png)

2018-08-10 07:06 UTC, varasev commented
When I reduce the width of the browser window, scroll down a little and click on menu, the menu items are not clickable and they're poorly visible because they're under the faded layout.

Also, I propose not to scroll the header (not to attach it to the top of the browser client area when scrolling) because it occupies a part of the small screen of a smartphone - it brings some discomfort for a user.

![image](https://user-images.githubusercontent.com/33550681/43943651-f832e52a-9c84-11e8-9323-50220bcfba33.png)

2018-08-10 19:12 UTC, gabitoesmiapodo commented
- Ballot description is shown with some words broken near the right border: Could we turn on a word wrapping? -> Yes, changed it so it's OK now.

- Padding is also needed here: -> Columns should be better separated now.

- Ballot time column is in the wrong place for min threshold and change proxy ballot types. You can find it if you click on Load More Ballots several times: -> OK, went very far into the "Load More" history and I think everything is fine now.

-  Some little defects with the search bar: -> Yeah, those were some states which were being overwritten. I'm not sure if there's something that could be done about the X, but the text is fine now.

- When I reduce the width of the browser window, scroll down a little and click on menu, the menu items are not clickable and they're poorly visible because they're under the faded layout. -> Fixed.

- Also, I propose not to scroll the header (not to attach it to the top of the browser client area when scrolling) because it occupies a part of the small screen of a smartphone - it brings some discomfort for a user. -> We should decide what to do with that. It takes some screen space, sure, but it also makes the menu available at all times. It could be very far away if the user loads more ballots a few times, and he / she should have to scroll up **a lot** if they reach the bottom.

2018-08-13 07:12 UTC, varasev commented
@gabitoesmiapodo Thanks for the fixes!

> We should decide what to do with that. It takes some screen space, sure, but it also makes the menu available at all times...

Ok, let's leave it as is.

Could you also make another ballot card that was added in the layout here: https://github.com/poanetwork/poa-dapps-voting/issues/164#issuecomment-412256495

We didn't yet implement this type of ballots in DApp, but you could add makeup of it in the `render` function of `src/components/BallotCard.jsx` just for a demo to see if it looks correct. Then we will comment out its code until the logic is implemented.

2018-08-13 07:15 UTC, varasev commented
@gabitoesmiapodo I mean this:

![poa_governance_app_sokol_2](https://user-images.githubusercontent.com/16716926/43989192-ba718af6-9d4d-11e8-924a-6f7661733f78.png)

2018-08-13 17:39 UTC, gabitoesmiapodo commented
@varasev 

Now the "Load more" button looks as you asked in https://github.com/poanetwork/poa-dapps-voting/issues/164#issuecomment-412537680

Working on https://github.com/poanetwork/poa-dapps-voting/pull/166#issuecomment-412428620 now.

2018-08-13 19:31 UTC, gabitoesmiapodo commented
@varasev 

What was asked in https://github.com/poanetwork/poa-dapps-voting/pull/166#issuecomment-412428620 should be done by now.

Testing code is in the components/BallotCard.jsx file, lines 445 to 503.

Original (No / Yes) code is commented out from line 505 to 541.

When this is tested / approved we should uncomment 505 to 541, and comment out 445 to 503.

2018-08-14 06:56 UTC, varasev commented
@gabitoesmiapodo ok, thank you. We also need to have the next columns for the new type of ballot:
- Proposer
- Proposed Receiver
- Funds Amount
- Ballot Time

as it's shown in https://github.com/poanetwork/poa-dapps-voting/pull/166#issuecomment-412428620

2018-08-14 16:45 UTC, vbaranov approved these changes

2018-08-16 13:12 UTC, gabitoesmiapodo commented
@varasev OK, there it is now.

Original code is commented out in src/components/BallotKeysCard.jsx lines 39 to 65.

<img width="1025" alt="new columns" src="https://user-images.githubusercontent.com/4015436/44210449-e5c80200-a13c-11e8-8707-46a73e0854e0.png">

2018-08-16 13:44 UTC, varasev requested changes

2018-08-16 13:44 UTC, varasev commented on src/assets/stylesheets/application/ballots/_about.scss
> +      white-space: nowrap;
@gabitoesmiapodo Let's return the word wrapping for the `name` (`proposer`) column. The previous look was better.

2018-08-16 13:53 UTC, gabitoesmiapodo commented
@varasev OK, done.

2018-08-16 14:44 UTC, varasev commented
@gabitoesmiapodo Ok, let's comment out the code for new ballot type and uncomment the original code. And then we'll merge all the changes.

2018-08-16 14:51 UTC, gabitoesmiapodo commented
@varasev Done.

2018-08-16 15:24 UTC, pashagonchar commented
@gabitoesmiapodo change logo please
<img width="239" alt="logo_1" src="https://user-images.githubusercontent.com/16716926/44218010-70caeb80-a181-11e8-93b3-2f173af9ac7b.png">
<img width="257" alt="logo_2" src="https://user-images.githubusercontent.com/16716926/44218158-c43d3980-a181-11e8-84cf-cf3d722bf99c.png">

https://zpl.io/VxlmwQ3

2018-08-16 16:17 UTC, gabitoesmiapodo commented
@pashagonchar Changed.

2018-08-17 08:23 UTC, varasev approved these changes

2018-08-17 08:24 UTC, merged